
[build-system]
requires = [
    "Cython",
    "setuptools",
    "wheel",
    "cythonpeg @ git+https://github.com/RaubCamaioni/CythonPEG.git"
]

build-backend = "setuptools.build_meta"

[project]
name="pyvoronoi"
requires-python = ">=3.8"