on:
    workflow_call:
jobs:
    build:
        name: Build distribution 📦
        runs-on: ubuntu-latest
        
        strategy:
        matrix:
            python-version: ["3.9", "3.10", "3.11", "3.12"]
    
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
    
        # Cython is only needed in build mode. No need to install it when publishing in Pypi
        - name: Install pypa/build
        run: python3 -m pip install build --user
    
        - name: Install wheel
        run: python3 -m pip install wheel --user
    
        - name: Install requirements
        run: python3 -m pip install -r requirements.txt      
        
        - name: Install dependencies
        run: python -m pip install Cython        
        
        - name: "Compile Cython file"
        run: python setup.py build_ext --inplace
    
        - name: Build a binary wheel and a source tarball
        run: python3 setup.py sdist
    
        - name: Remove dev file
        run: rm dev 
        
        - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
            name: python-package-distributions
            path: dist/
