name: Build distribution

on:
    workflow_call:
        inputs:
            config-path:
                required: false
                type: string

jobs:
    build:
        name: Build on ${{ matrix.os }} using ${{ matrix.python }} 📦
        runs-on: ${{ matrix.os }}
        
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python: ["3.10", "3.11", "3.12"]
    
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python }} ${{ matrix.os }}
              uses: actions/setup-python@v5


            # You can test your matrix by printing the current Python version
            - name: Display Python version
              run: python -c "import sys; print(sys.version)"

            - name: Install cibuildwheel
              run: python -m pip install cibuildwheel==2.18.1              

            # - name: Install development requirements
            #   run: python -m pip install -r requirements_dev.txt

            # - name: "Install locally for testing"
            #   run: python setup.py test  

            # - name: "Compile Cython file"
            #   run: python setup.py build_ext

            - name: Build wheels
              run: python -m cibuildwheel --output-dir wheelhouse
              env:
                CIBW_BEFORE_BUILD: pip install Cython
                CIBW_BUILD_VERBOSITY: 3
                CIBW_BUILD: ${{ matrix.python }}

            - uses: actions/upload-artifact@v4
              with:
                name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
                path: ./wheelhouse/*.whl 