name: Build distribution

on:

    workflow_call:
        inputs:
            config-path:
                required: false    
    jobs:
    call-build:
        # uses: ./.github/workflows/build.yaml
    build:
        name: Build distribution 📦
        runs-on: ubuntu-latest
        
        strategy:
        matrix:
            python-version: ["3.9", "3.10", "3.11", "3.12"]
    
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
    
        # Cython is only needed in build mode. No need to install it when publishing in Pypi
        - name: Install pypa/build
        run: python3 -m pip install build --user