name: Build distribution

on:
    workflow_call:
        inputs:
            config-path:
                required: false    
<<<<<<< HEAD
jobs:
=======
<<<<<<< HEAD
jobs:
=======
    jobs:
    call-build:
        # uses: ./.github/workflows/build.yaml
>>>>>>> 02b7e4a5e14f08f157bf8a5b90efe58825875401
>>>>>>> c2a391f6361e802d196b7d6af440a82e085cd7a0
    build:
        name: Build distribution 📦
        runs-on: ubuntu-latest
        
        strategy:
        matrix:
            python-version: ["3.9", "3.10", "3.11", "3.12"]
    
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
    
        # Cython is only needed in build mode. No need to install it when publishing in Pypi
        - name: Install pypa/build
        run: python3 -m pip install build --user