on:
  push:
    # A matching negative pattern after a positive match will exclude the ref again.
    branches:
      - '**'
    tags-ignore:
      - v*.*

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
      
